export interface Beer {
  abv:number,
  attenuation_level:number,
  boil_volume:{value,unit},
  brewers_tips:String,
  contributed_by:String,
  description:String,
  ebc:number,
  first_brewed:String,
  food_pairing:[String],
  ibu:number,
  id:number,
  image_url:String,
  ingredients:{malt: Array<Object>, hops: Array<Object>, yeast: String},
  method:{mash_temp:Array<{temp,duration}>, fermentation:Object, twist: null},
  name:String,
  ph:number,
  srm:number,
  similarBeers:Array<Beer>,
  tagline:String,
  target_fg:number,
  target_og:number,
  volume:{value,unit}
}
